# Calculate average throughput for long read sequencing data

PREFIX sos: <http://purl.jp/bio/10/quanto/ontology/sos#>
PREFIX quanto: <http://purl.jp/bio/10/quanto/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX pav: <http://purl.org/pav/>
PREFIX sio: <http://semanticscience.org/resource/>

SELECT (AVG(?total_sequences AS ?average_throughput))
FROM <http://quanto.dbcls.jp>
WHERE {
  ?quanto dct:identifier ?id;
    sio:SIO_000216 [
      a sos:TotalSequences;
        sio:SIO_000300 ?total_sequences;
    ];
    sio:SIO_000216 [
      a sos:MedianBaseCallQuality;
        sio:SIO_000300 ?median_bc_quality;
    ];
    sio:SIO_000216 [
      a sos:MedianSequenceLength;
        sio:SIO_000300 ?median_seq_length;
    ].
  FILTER(?median_seq_length > 500).
}
